openapi: 3.0.3
info:
  title: Calculadora Eléctrica RD - Sprint 8 API
  version: 0.1.0
paths:
  /projects:
    get:
      summary: Listar proyectos (paginado)
      parameters:
        - in: query; name: page; schema: { type: integer, default: 1 }
        - in: query; name: pageSize; schema: { type: integer, default: 10 }
        - in: query; name: sort; schema: { type: string }
        - in: query; name: order; schema: { type: string, enum: [asc, desc], default: asc }
        - in: query; name: q; schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items: { $ref: '#/components/schemas/Project' }
                  total: { type: integer }
                  page: { type: integer }
                  pageSize: { type: integer }
  /ai/evaluate:
    post:
      summary: Evaluación IA de un proyecto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                projectId: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/AiEvaluation' }
  /ai/suggestions:
    get:
      summary: Sugerencias IA
      parameters:
        - in: query; name: projectId; schema: { type: string }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  suggestions:
                    type: array
                    items: { $ref: '#/components/schemas/AiSuggestion' }
components:
  schemas:
    Project:
      type: object
      properties:
        id: { type: string }
        name: { type: string }
        owner: { type: string }
        apparentPowerKVA: { type: number }
        circuits: { type: integer }
        updatedAt: { type: string, format: date-time }
    AiEvaluation:
      type: object
      properties:
        score: { type: integer }
        alerts:
          type: array
          items:
            type: object
            properties:
              code: { type: string }
              severity: { type: string, enum: [info, warn, error] }
              message: { type: string }
        hints:
          type: array
          items: { type: string }
    AiSuggestion:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        description: { type: string }
