version: '3.8'

services:
  # Ollama - LLM Local
  ollama:
    image: ollama/ollama:latest
    container_name: electridom-ollama
    ports:
      - '11434:11434'
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    # healthcheck:
    #   test: ['CMD', 'curl', '-f', 'http://localhost:11434/api/version']
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 30s
    restart: unless-stopped
    networks:
      - electridom-network

  # Open WebUI (Opcional) - Interfaz web para Ollama
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: electridom-openwebui
    ports:
      - '3001:8080'
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - WEBUI_SECRET_KEY=your-secret-key-here
      - DEFAULT_USER_ROLE=admin
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - electridom-network

volumes:
  ollama_data:
    driver: local

networks:
  electridom-network:
    external: true
