openapi: 3.0.3
info:
  title: Calculadora Eléctrica RD – API Sprint 10
  version: 1.0.0
paths:
  /proyectos/{id}/resultados:
    get:
      summary: Resultados normativos del proyecto (circuitos, protecciones, conductores)
      parameters:
        - in: path
          name: id
          schema: { type: integer }
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  proyectoId: { type: integer }
                  circuitos:
                    type: array
                    items:
                      type: object
                      properties:
                        id: { type: integer }
                        ambienteId: { type: integer }
                        tipo: { type: string, enum: [IUG, TUG, IUE, TUE] }
                        potenciaVA: { type: integer }
                        corrienteA: { type: number }
                        proteccion:
                          type: object
                          properties:
                            tipo: { type: string }
                            capacidadA: { type: integer }
                            curva: { type: string }
                        conductor:
                          type: object
                          properties:
                            calibreAWG: { type: string }
                            material: { type: string }
                            capacidadA: { type: integer }
