version: '3.8'

services:
  api:
    build: .
    container_name: electridom-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=electridom
      - DATABASE_PASSWORD=electridom
      - DATABASE_NAME=electridom
      - JWT_SECRET=your-super-secret-jwt-key-change-in-production
      - JWT_EXPIRES_IN=900s
      - RULE_CACHE_TTL_MS=60000
      - APPLY_MIGRATIONS_ON_STARTUP=true
    depends_on:
      - mariadb
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - electridom-network

  mariadb:
    image: mariadb:11
    container_name: electridom-mariadb
    environment:
      - MARIADB_USER=electridom
      - MARIADB_PASSWORD=electridom
      - MARIADB_DATABASE=electridom
      - MARIADB_ROOT_PASSWORD=rootpassword
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./src/database/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-u',
          'electridom',
          '-pelectridom',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - electridom-network

volumes:
  mariadb_data:
    driver: local

networks:
  electridom-network:
    driver: bridge
